### ISSUE TITLE
IRepository.cs Extensions 

### ISSUE THREAD

**Issue by zyz** [philieu/EntityFramework.Repository#1]
Hi,
Your EntityFramework.Repository is very good,  
but the IRepository to provide more interface will be better. 
such as: Find(primary key), single table page, etc.
I think in the framework using EntityFramework Extended will be better.
To provide a common interface IBaseService.cs and implementation classes BaseService.cs will be more perfect. 
For example: 

IBaseService.cs
public interface IBaseService<TEntity>  where TEntity : class
    {
        void Delete(TEntity entity);
        void Insert(TEntity entity);
        void Update(TEntity entity);
    }
BaseService.cs
public class BaseService<TContext, TEntity> : IBaseService<TEntity>
        where TEntity : class
        where TContext : IDbContext
    {
        protected IUnitOfWork<TContext> _unitOfWork;
        protected IRepository<TContext, TEntity> _entityRepository;

```
    public BaseService(IUnitOfWork<TContext> unitOfWork, IRepository<TContext, TEntity> entityRepository)
    {
        this._unitOfWork = unitOfWork;
        this._entityRepository = entityRepository;
    }


    public void Delete(TEntity entity)
    {
        _entityRepository.Delete(entity);
        _unitOfWork.SaveChanges();
    }

    public void Insert(TEntity entity)
    {
        _entityRepository.Insert(entity);
        _unitOfWork.SaveChanges();
    }

    public void Update(TEntity entity)
    {
        _entityRepository.Update(entity);
        _unitOfWork.SaveChanges();
    }
```

}
Next Database BaseService
public class RedisBaseService<TEntity> : BaseService<IRedis2Context, TEntity>
        where TEntity : class
    {
        private static readonly ContextAdaptor<IRedis2Context> contextAdapter = new ContextAdaptor<IRedis2Context>(new Redis2Context());

```
    public RedisBaseService() : base(new UnitOfWork<IRedis2Context>(contextAdapter), new Repository<IRedis2Context, TEntity>(contextAdapter))
    {
    }
}
```

Next
IUserService.cs
public interface IUserService : IBaseService<User>
    {
        void Add(User user);
    }
UserService.cs
public class UserService : RedisBaseService<User>, IUserService
    {
       //I don't know this problem?
       //I think here the database context should be from base class RedisBaseService.cs inheritance 
       private IRepository<IRedis2Context, Role> _roleRepository;

```
    public UserService(IRepository<IRedis2Context, Role> roleRepository)
    {
        this._roleRepository = roleRepository;
    }
    public void Add(User user)
    {
        _entityRepository.Insert(user);
        _unitOfWork.SaveChanges();
    }
}
```

The above example code just for the sake of multidatabase, single table the public interface of reuse

**Comment by zyz** [comment]
Hope you put IBaseService BaseService and the above suggestion packaging in 
EntityFramework.Repository

**Comment by zyz** [comment]
Thank you very much!

**Comment by zyz** [comment]
Looking forward to your update...

**Comment by philieu** [comment]
Hi @zyz,

Thanks for the feedback and suggestion. I'm planning to spend some time in the coming days to work on the library and will definitely look at your suggestion.

Cheers.
